// Kelappa Landing — copy (English + Russian). Language is picked by /lang.js.

const { useState, useEffect, useRef } = React;

const COPY = {
  en: {
    meta: { title: 'Kelappa — Apps for people with ADHD' },
    nav: { apps: 'Apps', principles: 'Principles', contact: 'Contact', lang: 'Language' },
    hero: {
      eyebrow: 'Kelappa · Bali',
      h_pre: 'Apps for people with',
      h_hl: 'ADHD',
      h_post: '.',
      sub: 'Get distracted, forget things, run late? Money slips away, numbers won\'t stick, important things fall out of your head? We make easy apps that quietly become part of your day and take these worries off your plate — until you stop thinking about them at all.',
      cta_primary: 'See the apps',
      cta_secondary: 'Read the manifesto',
    },
    manifesto: {
      eyebrow: 'Why we exist',
      h: 'The world is loud. Software does not have to be.',
      p1: 'Most apps are built to capture you — streaks, notifications, autoplay, infinite feeds. For a restless brain, that is not a tool. That is another thing to manage.',
      p2: 'We grew up with ADHD. We know what it costs when an app punishes a missed day, or hides what you typed, or asks one more question before saving. So we make the other kind.',
      p3: 'Small apps. Quiet by default. They wait. They remember. They never make you feel behind.',
    },
    principles: {
      eyebrow: 'How we build',
      h: 'Six rules we will not break.',
      items: [
        { n: '01', title: 'One thing per screen', body: 'A screen asks for one decision. Never two, never a sidebar of seventeen.' },
        { n: '02', title: 'No streaks, no shame', body: 'Skipped Tuesday? The app does not notice. Habits are kept, not enforced.' },
        { n: '03', title: 'Always saved', body: 'Type anywhere. Close anywhere. It is there when you come back.' },
        { n: '04', title: 'Quiet by default', body: 'Zero notifications until you ask. No badges. No little red dots.' },
        { n: '05', title: 'Predictable shape', body: 'The thing in the top-left is the thing in the top-left. Every time. Forever.' },
        { n: '06', title: 'Made for the worst day', body: 'If it works on a foggy Monday, it works on any day.' },
      ],
    },
    apps: {
      eyebrow: 'Our apps',
      h: 'Small tools that get out of your way.',
      sub: 'Each one removes one piece of daily friction that an ADHD brain runs into ten times a day. Most of them you can use today.',
      items: [
        {
          name: 'CCV', sub: 'the notch · file portal',
          tagline: 'Drop a file in your notch. Pick it up anywhere.',
          desc: 'The MacBook notch becomes a parking spot for files. Drag something in. Walk to another screen. Drag it out. No AirDrop dance, no "where did I save that".',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'VText', sub: 'voice → text, anywhere',
          tagline: 'Hold two keys. Speak. Paste.',
          desc: 'Press ⌘⇧, say what you mean, release. The text lands wherever your cursor is. Ask the AI to shorten it, soften it, or translate it — then paste.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'FloFi', sub: 'finance, gently',
          tagline: 'Money you can actually look at.',
          desc: 'Track and plan your money without the spreadsheet panic. Calm categories, no judgement, no scary red. Built for brains that forget Tuesday existed.',
          platforms: ['iOS', 'macOS'],
          available: true,
        },
        {
          name: 'Switcher', sub: 'ru / en · keyboard',
          tagline: 'Wrong layout? Already fixed.',
          desc: 'Typed "руддщ" when you meant "hello"? Switcher notices, swaps the layout, and rewrites the word. You never have to retype, or hunt for the menu bar icon again.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'Telesufler', sub: 'floating script · for your eyes only',
          tagline: 'Your script. Hidden when you share.',
          desc: 'Park a small window just under your built-in camera and read from it while looking into the lens. It floats over Zoom and Meet — and when you turn screen sharing on, viewers never see it. Toggle hide with ⌥⇧.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'Onit', sub: 'one task · always in sight',
          tagline: 'Remember what you sat down to do.',
          desc: 'Write the task once and it parks in the corner of your screen, above every window. Wander off into Telegram and it turns red and starts to breathe — it reminds, it does not punish. Press done, say in one line how it went, and it lands in your success diary: by the evening you can see what the day actually was, instead of wondering where it went.',
          platforms: ['macOS'],
          available: true,
        },
      ],
      status: 'Available',
      cta: 'Open',
      download: 'Download',
    },
    cta: {
      eyebrow: 'Begin',
      h_pre: 'Try',
      h_hl: 'one app',
      h_post: ' today.',
      sub: 'You do not have to commit. Open it once. Use it for the one thing it does. See if it stays out of your way.',
      btn: 'See all apps',
    },
    footer: {
      tag: 'A small studio crafting calm apps for Apple platforms.',
      cols: [
        { h: 'Apps', l: ['CCV', 'VText', 'FloFi', 'Switcher', 'Telesufler', 'Onit'] },
      ],
      legal: '© 2026 Kelappa · Made slowly in Ubud · kelappa.studio',
    },
    mocks: {
      ccv: { file: 'villa_invoice.pdf', parked: 'parked · drag to take', eyebrow: 'The Portal', h: 'Drop anything. Take it anywhere.', count: '3 items parked' },
      vtext: {
        doc_title: 'Reply to Nyoman about the villa',
        doc_l1: 'Hi Nyoman, thanks for getting back. I wanted to follow up on the',
        doc_l2: 'invoice',
        listening: '⌘⇧ · listening · 0:08',
        said: '"could we move the payment to next monday since the bank holiday is on friday and i don\'t want this to get stuck in limbo"',
        actions: ['Insert', 'Shorter', 'Softer', 'Translate → EN'],
      },
      flofi: {
        eyebrow: 'This week · gentle view', left: '· left for the month', track: '↑ you are on track',
        days: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
        cats: ['Food & coffee', 'Rent & home', 'Fun & other'],
        today_pre: 'Today you have', today_post: 'for fun.',
      },
      switcher: {
        eyebrow: 'Compose · message', greeting: 'Hi Wira,',
        wrong: 'руддщ', right: 'hello', l1: '— could you take a look at the build?', l2: 'I think the api thing is broken again.',
        badge: 'RU→EN', toast: 'Switched to English', pair: '"руддщ" → "hello"',
      },
      telesufler: {
        eyebrow: 'screen sharing · slide 4 / 12', h: 'Q3 plan — three bets',
        bullets: ['Launch the chat bot to 20 villas', 'Wire up the new pricing engine', 'Ship Telesufler 1.1'],
        you: 'You', on_top: 'always on top',
        prev: 'Hi everyone, thanks for jumping on.', line: 'Three updates — shipping, hiring, Bali offsite.', next: 'First — the bot is live in beta.',
        hidden: 'Hidden when you share screen',
      },
      onit: {
        doc_eyebrow: 'draft · q3 plan', doc_h: 'Three bets for Q3',
        task: 'Write the Q3 plan', running: '24:08 · running', still_on: 'still on: Write the Q3 plan',
        after: 'after 15 s in a messenger', diary: 'success diary · today', ask: '✎ what came out of it?',
        rows: [
          { name: 'Q3 plan — three bets', time: '1h 20m', result: 'sent to the team, two bets cut' },
          { name: 'Reply to Nyoman',      time: '12m',    result: 'invoice moved to Monday' },
          { name: 'Fix the villa feed',   time: '2h 05m', result: null },
        ],
        total: '3h 37m',
      },
    },
  },

  ru: {
    meta: { title: 'Kelappa — приложения для людей с СДВГ' },
    nav: { apps: 'Приложения', principles: 'Принципы', contact: 'Контакты', lang: 'Язык' },
    hero: {
      eyebrow: 'Kelappa · Бали',
      h_pre: 'Приложения для людей с',
      h_hl: 'СДВГ',
      h_post: '.',
      sub: 'Отвлекаетесь, забываете, опаздываете? С деньгами и цифрами тяжело, а важное вылетает из головы? Мы делаем удобные приложения, которые незаметно становятся частью вашей жизни и берут эти заботы на себя — так, что вы перестаёте о них думать.',
      cta_primary: 'Смотреть приложения',
      cta_secondary: 'Прочитать манифест',
    },
    manifesto: {
      eyebrow: 'Зачем мы это делаем',
      h: 'Мир шумный. Программы не обязаны быть такими же.',
      p1: 'Большинство приложений сделаны, чтобы вас удерживать: серии дней, уведомления, автозапуск видео, бесконечные ленты. Для беспокойного мозга это не инструмент, а ещё одна вещь, за которой надо следить.',
      p2: 'Мы сами живём с СДВГ. Мы знаем, чего стоит приложение, которое наказывает за пропущенный день, прячет то, что вы написали, или задаёт ещё один вопрос перед сохранением. Поэтому делаем по-другому.',
      p3: 'Маленькие приложения. Тихие по умолчанию. Они ждут. Они помнят. Они никогда не дают почувствовать, что вы отстали.',
    },
    principles: {
      eyebrow: 'Как мы делаем',
      h: 'Шесть правил, которые мы не нарушаем.',
      items: [
        { n: '01', title: 'Один экран — одно дело', body: 'Экран просит принять одно решение. Не два и не боковую панель из семнадцати пунктов.' },
        { n: '02', title: 'Без серий и без стыда', body: 'Пропустили вторник? Приложение не заметит. Привычки поддерживают, а не заставляют.' },
        { n: '03', title: 'Всё сохраняется', body: 'Пишите где угодно, закрывайте когда угодно. Вернётесь — всё на месте.' },
        { n: '04', title: 'Тихо по умолчанию', body: 'Ноль уведомлений, пока вы сами не попросите. Ни значков, ни красных точек.' },
        { n: '05', title: 'Всё на своих местах', body: 'Что было в левом верхнем углу, там и останется. Всегда.' },
        { n: '06', title: 'Для самого тяжёлого дня', body: 'Если работает в туманный понедельник — сработает в любой день.' },
      ],
    },
    apps: {
      eyebrow: 'Наши приложения',
      h: 'Небольшие инструменты, которые не мешают.',
      sub: 'Каждое убирает одну мелкую помеху, об которую мозг с СДВГ спотыкается по десять раз на дню. Большинством можно пользоваться уже сегодня.',
      items: [
        {
          name: 'CCV', sub: 'чёлка · портал для файлов',
          tagline: 'Бросьте файл в чёлку. Заберите где угодно.',
          desc: 'Чёлка MacBook превращается в парковку для файлов. Перетащили туда файл, перешли на другой экран — вытащили обратно. Никаких танцев с AirDrop и вопросов «куда же я это сохранил».',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'VText', sub: 'голос → текст, где угодно',
          tagline: 'Зажмите две клавиши. Скажите. Вставьте.',
          desc: 'Нажмите ⌘⇧, скажите, что хотели, отпустите. Текст появится там, где стоит курсор. Попросите ИИ сократить, смягчить или перевести — и вставляйте.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'FloFi', sub: 'финансы, бережно',
          tagline: 'Деньги, на которые не страшно смотреть.',
          desc: 'Учёт и планирование денег без паники над таблицами. Спокойные категории, никаких упрёков и пугающего красного. Для тех, кто забывает, что вообще был вторник.',
          platforms: ['iOS', 'macOS'],
          available: true,
        },
        {
          name: 'Switcher', sub: 'ru / en · раскладка',
          tagline: 'Не та раскладка? Уже исправлено.',
          desc: 'Набрали «ghbdtn», а хотели «привет»? Switcher заметит, переключит раскладку и перепишет слово. Не придётся ни перепечатывать, ни искать значок в строке меню.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'Telesufler', sub: 'плавающий текст · видно только вам',
          tagline: 'Ваш текст. Невидимый при демонстрации.',
          desc: 'Поставьте маленькое окно прямо под камерой и читайте с него, глядя в объектив. Оно висит поверх Zoom и Meet, а когда включаете демонстрацию экрана, зрители его не видят. Скрыть и показать — ⌥⇧.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'Onit', sub: 'одна задача · всегда на виду',
          tagline: 'Помните, зачем сели за компьютер.',
          desc: 'Запишите задачу — и она встанет в углу экрана поверх всех окон. Отвлеклись на Telegram — плашка краснеет и начинает «дышать»: напоминает, а не наказывает. Нажмите «готово», в одной строке опишите, что получилось, — и это попадёт в дневник успеха. Вечером видно, каким был день на самом деле, а не «куда он делся».',
          platforms: ['macOS'],
          available: true,
        },
      ],
      status: 'Доступно',
      cta: 'Открыть',
      download: 'Скачать',
    },
    cta: {
      eyebrow: 'Начать',
      h_pre: 'Попробуйте',
      h_hl: 'одно приложение',
      h_post: ' сегодня.',
      sub: 'Ничего не нужно обещать. Откройте один раз. Используйте для того единственного дела, которое оно делает. Посмотрите, получится ли оно незаметным.',
      btn: 'Все приложения',
    },
    footer: {
      tag: 'Небольшая студия, которая делает спокойные приложения для платформ Apple.',
      cols: [
        { h: 'Приложения', l: ['CCV', 'VText', 'FloFi', 'Switcher', 'Telesufler', 'Onit'] },
      ],
      legal: '© 2026 Kelappa · Сделано не спеша в Убуде · kelappa.studio',
    },
    mocks: {
      ccv: { file: 'villa_invoice.pdf', parked: 'на парковке · тяните, чтобы взять', eyebrow: 'Портал', h: 'Положили — забрали где угодно.', count: '3 файла ждут' },
      vtext: {
        doc_title: 'Ответ Ньоману по вилле',
        doc_l1: 'Ньоман, привет, спасибо, что ответил. Хотел уточнить по поводу',
        doc_l2: 'счёта',
        listening: '⌘⇧ · слушаю · 0:08',
        said: '«слушай а можно перенести оплату на следующий понедельник а то в пятницу выходной и не хочу чтобы всё зависло»',
        actions: ['Вставить', 'Короче', 'Мягче', 'Перевести → EN'],
      },
      flofi: {
        eyebrow: 'Эта неделя · спокойный вид', left: '· осталось на месяц', track: '↑ всё идёт по плану',
        days: ['П', 'В', 'С', 'Ч', 'П', 'С', 'В'],
        cats: ['Еда и кофе', 'Жильё', 'Развлечения'],
        today_pre: 'Сегодня можно', today_post: 'на радости.',
      },
      switcher: {
        eyebrow: 'Новое · сообщение', greeting: 'Вира, привет!',
        wrong: 'ghbdtn', right: 'привет', l1: '— глянешь сборку?', l2: 'Кажется, api опять сломался.',
        badge: 'EN→RU', toast: 'Переключено на русский', pair: '«ghbdtn» → «привет»',
      },
      telesufler: {
        eyebrow: 'демонстрация экрана · слайд 4 / 12', h: 'План на Q3 — три ставки',
        bullets: ['Запустить чат-бота на 20 виллах', 'Подключить новый расчёт цен', 'Выпустить Telesufler 1.1'],
        you: 'Вы', on_top: 'поверх окон',
        prev: 'Всем привет, спасибо, что подключились.', line: 'Три новости — релиз, найм и выезд на Бали.', next: 'Первое — бот уже в бете.',
        hidden: 'Не видно при демонстрации',
      },
      onit: {
        doc_eyebrow: 'черновик · план q3', doc_h: 'Три ставки на Q3',
        task: 'План на Q3', running: '24:08 · идёт', still_on: 'в работе: План на Q3',
        after: 'через 15 с в мессенджере', diary: 'дневник успеха · сегодня', ask: '✎ что получилось?',
        rows: [
          { name: 'План на Q3 — три ставки', time: '1 ч 20 м', result: 'отправил команде, две ставки убрали' },
          { name: 'Ответ Ньоману',           time: '12 м',     result: 'оплату перенесли на понедельник' },
          { name: 'Починить фид вилл',        time: '2 ч 05 м', result: null },
        ],
        total: '3 ч 37 м',
      },
    },
  },
};

Object.assign(window, { COPY });
