// Kelappa Landing — copy (English + Russian). Language is picked by /lang.js.

const { useState, useEffect, useRef } = React;

const COPY = {
  en: {
    meta: { title: 'Kelappa — Apps for people with ADHD' },
    nav: { apps: 'Apps', principles: 'Principles', contact: 'Contact', lang: 'Language' },
    hero: {
      eyebrow: 'Kelappa · Bali',
      h_pre: 'Apps for people with',
      h_hl: 'ADHD',
      h_post: '.',
      sub: 'Get distracted, forget things, run late? Money slips away, numbers won\'t stick, important things fall out of your head? We make easy apps that quietly become part of your day and take these worries off your plate — until you stop thinking about them at all.',
      cta_primary: 'See the apps',
      cta_secondary: 'Read the manifesto',
    },
    manifesto: {
      eyebrow: 'Why we exist',
      h: 'We live with ADHD ourselves.',
      p1: 'These days everyone says they have a bit of ADHD. But when you actually live with it, there is nothing to compare it to. The dumb slip-ups drive you mad. It drives you mad that they annoy other people. It drives you mad that they eat into your life.',
      p2: 'So we build apps for ourselves — to keep up with the world on equal terms. And we share them with you, because we have been where you are and we know how it feels. Most of those slip-ups can be fixed with technology and AI.',
      p3: 'Someone with ADHD, AI and the right crutches might just be a superhuman. No promises, though.',
    },
    principles: {
      eyebrow: 'How we build',
      h: 'Six rules we will not break.',
      items: [
        { n: '01', title: 'One thing per screen', body: 'A screen asks for one decision. Never two, never a sidebar of seventeen.' },
        { n: '02', title: 'No streaks, no shame', body: 'Skipped Tuesday? The app does not notice. Habits are kept, not enforced.' },
        { n: '03', title: 'Always saved', body: 'Type anywhere. Close anywhere. It is there when you come back.' },
        { n: '04', title: 'Quiet by default', body: 'Zero notifications until you ask. No badges. No little red dots.' },
        { n: '05', title: 'Predictable shape', body: 'The thing in the top-left is the thing in the top-left. Every time. Forever.' },
        { n: '06', title: 'Made for the worst day', body: 'If it works on a foggy Monday, it works on any day.' },
      ],
    },
    apps: {
      eyebrow: 'Our apps',
      h: 'Small tools that get out of your way.',
      sub: 'Each one removes one piece of daily friction that an ADHD brain runs into ten times a day. Most of them you can use today.',
      items: [
        {
          name: 'CCV', sub: 'the notch · file portal',
          tagline: 'Tired of dragging files between windows? Just drop them in the notch.',
          desc: 'A simple app that turns your MacBook notch into extra space for files. Drop a file in, calmly switch to the window you need, and drag it out there. Your files never get lost again.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'VText', sub: 'voice → text, anywhere',
          tagline: 'Hate typing, but nobody likes voice messages? Just talk — VText types.',
          desc: 'Hold two keys and speak. The text appears wherever your cursor is — and can be sent automatically. The other person gets a normal message, not a voice note.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'FloFi', sub: 'finance, gently',
          tagline: 'Anxious about money? Open your money calendar.',
          desc: 'Not sure when money comes in, when bills are due, or whether it will be enough? FloFi works like a calendar for your money: see where you will be in a week, a month, half a year or a year — as deep as you want to go. It is easier than it sounds. Of everything we have made, it was the hardest to build and it is the most valuable to use. Just give it a chance.',
          platforms: ['iOS', 'macOS'],
          available: true,
        },
        {
          name: 'Switcher', sub: 'ru / en · keyboard',
          tagline: 'Typed a whole line and got "руддщ"? Switcher fixes it.',
          desc: 'You type, look up at the screen — and it all came out in the wrong layout. Switcher notices, switches the layout and rewrites the words. Nothing to retype.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'Telesufler', sub: 'floating script · for your eyes only',
          tagline: 'Jumping from topic to topic? Keep your script in front of you.',
          desc: 'A Zoom call, a presentation, a screen recording. Add your text to Telesufler and it appears right by your camera. Look into the lens, say it out loud, and never lose the thread. Viewers never see it, even when you share your screen.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'Onit', sub: 'one task · always in sight',
          tagline: 'Opened Telegram and forgot what you were doing? Onit reminds you.',
          desc: 'You sit down to a task. Then a message in Telegram or WhatsApp, from there a link to YouTube, then a chat with ChatGPT about it… and the task is gone. Onit keeps a small plate on your screen showing what you are doing right now, and nudges you back when you wander off.',
          platforms: ['macOS'],
          available: true,
        },
      ],
      status: 'Available',
      cta: 'Open',
      download: 'Download',
    },
    cta: {
      eyebrow: 'Begin',
      h_pre: 'Try',
      h_hl: 'one app',
      h_post: ' today.',
      sub: 'You do not have to commit. Open it once. Use it for the one thing it does. See if it stays out of your way.',
      btn: 'See all apps',
    },
    footer: {
      tag: 'A small studio crafting calm apps for Apple platforms.',
      cols: [
        { h: 'Apps', l: ['CCV', 'VText', 'FloFi', 'Switcher', 'Telesufler', 'Onit'] },
      ],
      legal: '© 2026 Kelappa · Made slowly in Ubud · kelappa.studio',
    },
    mocks: {
      ccv: { file: 'villa_invoice.pdf', parked: 'parked · drag to take', eyebrow: 'The Portal', h: 'Drop anything. Take it anywhere.', count: '3 items parked' },
      vtext: {
        doc_title: 'Reply to Nyoman about the villa',
        doc_l1: 'Hi Nyoman, thanks for getting back. I wanted to follow up on the',
        doc_l2: 'invoice',
        listening: '⌘⇧ · listening · 0:08',
        said: '"could we move the payment to next monday since the bank holiday is on friday and i don\'t want this to get stuck in limbo"',
        actions: ['Insert', 'Shorter', 'Softer', 'Translate → EN'],
      },
      flofi: {
        eyebrow: 'This week · gentle view', left: '· left for the month', track: '↑ you are on track',
        days: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
        cats: ['Food & coffee', 'Rent & home', 'Fun & other'],
        today_pre: 'Today you have', today_post: 'for fun.',
      },
      switcher: {
        eyebrow: 'Compose · message', greeting: 'Hi Wira,',
        wrong: 'руддщ', right: 'hello', l1: '— could you take a look at the build?', l2: 'I think the api thing is broken again.',
        badge: 'RU→EN', toast: 'Switched to English', pair: '"руддщ" → "hello"',
      },
      telesufler: {
        eyebrow: 'screen sharing · slide 4 / 12', h: 'Q3 plan — three bets',
        bullets: ['Launch the chat bot to 20 villas', 'Wire up the new pricing engine', 'Ship Telesufler 1.1'],
        you: 'You', on_top: 'always on top',
        prev: 'Hi everyone, thanks for jumping on.', line: 'Three updates — shipping, hiring, Bali offsite.', next: 'First — the bot is live in beta.',
        hidden: 'Hidden when you share screen',
      },
      onit: {
        doc_eyebrow: 'draft · q3 plan', doc_h: 'Three bets for Q3',
        task: 'Write the Q3 plan', running: '24:08 · running', still_on: 'still on: Write the Q3 plan',
        after: 'after 15 s in a messenger', diary: 'success diary · today', ask: '✎ what came out of it?',
        rows: [
          { name: 'Q3 plan — three bets', time: '1h 20m', result: 'sent to the team, two bets cut' },
          { name: 'Reply to Nyoman',      time: '12m',    result: 'invoice moved to Monday' },
          { name: 'Fix the villa feed',   time: '2h 05m', result: null },
        ],
        total: '3h 37m',
      },
    },
  },

  ru: {
    meta: { title: 'Kelappa — приложения для людей с СДВГ' },
    nav: { apps: 'Приложения', principles: 'Принципы', contact: 'Контакты', lang: 'Язык' },
    hero: {
      eyebrow: 'Kelappa · Бали',
      h_pre: 'Приложения для людей с',
      h_hl: 'СДВГ',
      h_post: '.',
      sub: 'Отвлекаетесь, забываете, опаздываете? С деньгами и цифрами тяжело, а важное вылетает из головы? Мы делаем удобные приложения, которые незаметно становятся частью вашей жизни и берут эти заботы на себя — так, что вы перестаёте о них думать.',
      cta_primary: 'Смотреть приложения',
      cta_secondary: 'Прочитать манифест',
    },
    manifesto: {
      eyebrow: 'Зачем мы это делаем',
      h: 'Мы сами живём с\u00a0СДВГ.',
      p1: 'Сейчас модно говорить, что СДВГ у всех. Но когда живёшь с этим каждый день, это ни с чем не спутаешь. Бесят глупые косяки. Бесит, что они бесят других. Бесит, что они мешают нормально жить.',
      p2: 'Поэтому мы делаем приложения для себя — чтобы жить и работать наравне со всеми. И делимся ими с вами: мы были на вашем месте и понимаем, что вы чувствуете. Большую часть этих косяков можно закрыть технологиями и искусственным интеллектом.',
      p3: 'СДВГшник с ИИ и правильными костылями — возможно, суперчеловек. Но это не точно.',
    },
    principles: {
      eyebrow: 'Как мы делаем',
      h: 'Шесть правил, которые мы не нарушаем.',
      items: [
        { n: '01', title: 'Один экран — одно дело', body: 'Экран просит принять одно решение. Не два и не боковую панель из семнадцати пунктов.' },
        { n: '02', title: 'Без серий и без стыда', body: 'Пропустили вторник? Приложение не заметит. Привычки поддерживают, а не заставляют.' },
        { n: '03', title: 'Всё сохраняется', body: 'Пишите где угодно, закрывайте когда угодно. Вернётесь — всё на месте.' },
        { n: '04', title: 'Тихо по умолчанию', body: 'Ноль уведомлений, пока вы сами не попросите. Ни значков, ни красных точек.' },
        { n: '05', title: 'Всё на своих местах', body: 'Что было в левом верхнем углу, там и останется. Всегда.' },
        { n: '06', title: 'Для самого тяжёлого дня', body: 'Если работает в туманный понедельник — сработает в любой день.' },
      ],
    },
    apps: {
      eyebrow: 'Наши приложения',
      h: 'Небольшие инструменты, которые не мешают.',
      sub: 'Каждое убирает одну мелкую помеху, об которую мозг с СДВГ спотыкается по десять раз на дню. Большинством можно пользоваться уже сегодня.',
      items: [
        {
          name: 'CCV', sub: 'чёлка · портал для файлов',
          tagline: 'Бесит перетаскивать файлы между окнами? Просто закиньте их в чёлку.',
          desc: 'Простое приложение, которое превращает чёлку MacBook в дополнительное место для файлов. Закинули файл, спокойно переключились на нужное окно — и вытащили его туда. Файлы больше нигде не теряются.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'VText', sub: 'голос → текст, где угодно',
          tagline: 'Бесит печатать, а голосовые никто не любит? Говорите — VText напишет.',
          desc: 'Зажмите две клавиши и говорите. Текст сам наберётся там, где стоит курсор, и может сразу отправиться. Собеседник получит обычное сообщение, а не голосовое.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'FloFi', sub: 'финансы, бережно',
          tagline: 'Страшно, что будет с деньгами? Откройте календарь своих денег.',
          desc: 'Непонятно, когда придут деньги, когда платить и хватит ли их? FloFi работает как календарь ваших денег: видно, что с ними будет через неделю, месяц, полгода или год — насколько захотите заморочиться. Это проще, чем кажется. Из всего, что мы сделали, это приложение было самым сложным в разработке — и оно самое ценное в жизни. Просто дайте ему шанс.',
          platforms: ['iOS', 'macOS'],
          available: true,
        },
        {
          name: 'Switcher', sub: 'ru / en · раскладка',
          tagline: 'Напечатали строку, а там «ghbdtn»? Switcher исправит.',
          desc: 'Бесит, когда печатаете, смотрите на экран — а всё набралось не в той раскладке. Switcher сам заметит, переключит раскладку и перепишет слова. Перепечатывать ничего не нужно.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'Telesufler', sub: 'плавающий текст · видно только вам',
          tagline: 'Скачете с темы на тему? Держите текст перед глазами.',
          desc: 'Звонок в Zoom, презентация, запись видео с экрана. Добавьте текст в Telesufler — он появится прямо у камеры. Вы смотрите в объектив, проговариваете текст и ни разу не сбиваетесь с темы. Зрители окно не видят, даже при демонстрации экрана.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'Onit', sub: 'одна задача · всегда на виду',
          tagline: 'Открыли Telegram и забыли, что делали? Onit напомнит.',
          desc: 'Сели делать задачу. Зашли в Telegram или WhatsApp, из сообщения — на YouTube, оттуда — в ChatGPT обсуждать… и уже не помните, что хотели сделать. Onit держит на экране плашку с тем, чем вы сейчас заняты, и напоминает вернуться к делу.',
          platforms: ['macOS'],
          available: true,
        },
      ],
      status: 'Доступно',
      cta: 'Открыть',
      download: 'Скачать',
    },
    cta: {
      eyebrow: 'Начать',
      h_pre: 'Попробуйте',
      h_hl: 'одно приложение',
      h_post: ' сегодня.',
      sub: 'Ничего не нужно обещать. Откройте один раз. Используйте для того единственного дела, которое оно делает. Посмотрите, получится ли оно незаметным.',
      btn: 'Все приложения',
    },
    footer: {
      tag: 'Небольшая студия, которая делает спокойные приложения для платформ Apple.',
      cols: [
        { h: 'Приложения', l: ['CCV', 'VText', 'FloFi', 'Switcher', 'Telesufler', 'Onit'] },
      ],
      legal: '© 2026 Kelappa · Сделано не спеша в Убуде · kelappa.studio',
    },
    mocks: {
      ccv: { file: 'villa_invoice.pdf', parked: 'на парковке · тяните, чтобы взять', eyebrow: 'Портал', h: 'Положили — забрали где угодно.', count: '3 файла ждут' },
      vtext: {
        doc_title: 'Ответ Ньоману по вилле',
        doc_l1: 'Ньоман, привет, спасибо, что ответил. Хотел уточнить по поводу',
        doc_l2: 'счёта',
        listening: '⌘⇧ · слушаю · 0:08',
        said: '«слушай а можно перенести оплату на следующий понедельник а то в пятницу выходной и не хочу чтобы всё зависло»',
        actions: ['Вставить', 'Короче', 'Мягче', 'Перевести → EN'],
      },
      flofi: {
        eyebrow: 'Эта неделя', left: '· до конца месяца', track: '↑ всё идёт по плану',
        days: ['П', 'В', 'С', 'Ч', 'П', 'С', 'В'],
        cats: ['Еда и кофе', 'Жильё', 'Развлечения'],
        today_pre: 'Сегодня можно', today_post: 'на радости.',
      },
      switcher: {
        eyebrow: 'Новое · сообщение', greeting: 'Вира, привет!',
        wrong: 'ghbdtn', right: 'привет', l1: '— глянешь сборку?', l2: 'Кажется, api опять сломался.',
        badge: 'EN→RU', toast: 'Переключено на русский', pair: '«ghbdtn» → «привет»',
      },
      telesufler: {
        eyebrow: 'демонстрация экрана · слайд 4 / 12', h: 'План на Q3 — три ставки',
        bullets: ['Запустить чат-бота на 20 виллах', 'Подключить новый расчёт цен', 'Выпустить Telesufler 1.1'],
        you: 'Вы', on_top: 'поверх окон',
        prev: 'Всем привет, спасибо, что подключились.', line: 'Три новости — релиз, найм и выезд на Бали.', next: 'Первое — бот уже в бете.',
        hidden: 'Не видно при демонстрации',
      },
      onit: {
        doc_eyebrow: 'черновик · план q3', doc_h: 'Три ставки на Q3',
        task: 'План на Q3', running: '24:08 · идёт', still_on: 'в работе: План на Q3',
        after: 'через 15 с в мессенджере', diary: 'дневник успеха · сегодня', ask: '✎ что получилось?',
        rows: [
          { name: 'План на Q3 — три ставки', time: '1 ч 20 м', result: 'отправил команде, две ставки убрали' },
          { name: 'Ответ Ньоману',           time: '12 м',     result: 'оплату перенесли на понедельник' },
          { name: 'Починить фид вилл',        time: '2 ч 05 м', result: null },
        ],
        total: '3 ч 37 м',
      },
    },
  },
};

Object.assign(window, { COPY });
