// Kelappa Landing\u00a0— copy (English + Russian). Language is picked by /lang.js.

const { useState, useEffect, useRef } = React;

const COPY = {
  en: {
    meta: { title: 'Kelappa\u00a0— Apps for people with ADHD' },
    nav: { apps: 'Apps', principles: 'Principles', contact: 'Contact', lang: 'Language' },
    hero: {
      eyebrow: 'Kelappa · Bali',
      h_pre: 'Apps for people with',
      h_hl: 'ADHD',
      h_post: '.',
      sub_q: 'Always forgetting things, getting distracted, running late?',
      sub_a: 'We make apps that remember for you.',
      cta_primary: 'See the apps',
      cta_secondary: 'Read the manifesto',
    },
    manifesto: {
      eyebrow: 'Why we exist',
      h: 'We live with ADHD ourselves.',
      p1: 'These days everyone says they have a bit of ADHD. But when you actually live with it, there is nothing to compare it to. The dumb slip-ups drive you mad. It drives you mad that they annoy other people. It drives you mad that they eat into your life.',
      p2: 'So we build apps for ourselves\u00a0— to keep up with the world on equal terms. And we share them with you, because we have been where you are and we know how it feels. Most of those slip-ups can be fixed with technology and AI.',
      p3: 'Someone with ADHD, AI and the right crutches might just be a superhuman. No promises, though.',
    },
    principles: {
      eyebrow: 'How we build',
      h: 'Six rules we will not break.',
      items: [
        { n: '01', title: 'One thing per screen', body: 'A screen asks for one decision. Never two, never a sidebar of seventeen.' },
        { n: '02', title: 'No streaks, no shame', body: 'Skipped Tuesday? The app does not notice. Habits are kept, not enforced.' },
        { n: '03', title: 'Always saved', body: 'Type anywhere. Close anywhere. It is there when you come back.' },
        { n: '04', title: 'Quiet by default', body: 'Zero notifications until you ask. No badges. No little red dots.' },
        { n: '05', title: 'Predictable shape', body: 'The thing in the top-left is the thing in the top-left. Every time. Forever.' },
        { n: '06', title: 'Made for the worst day', body: 'If it works on a foggy Monday, it works on any day.' },
      ],
    },
    apps: {
      eyebrow: 'Our apps',
      h: 'Small tools that get out of your way.',
      sub: 'Each one removes one piece of daily friction that an ADHD brain runs into ten times a day. Most of them you can use today.',
      items: [
        {
          name: 'CCV', sub: 'the notch · file portal',
          tagline: 'Tired of dragging files between windows? Just drop them in the notch.',
          desc: 'A simple app that turns your MacBook notch into extra space for files. Drop a file in, calmly switch to the window you need, and drag it out there. Your files never get lost again.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'VText', sub: 'voice → text, anywhere',
          tagline: 'Hate typing, but nobody likes voice messages? Just talk\u00a0— VText types.',
          desc: 'Hold two keys and speak. The text appears wherever your cursor is\u00a0— and can be sent automatically. The other person gets a normal message, not a voice note.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'FloFi', sub: 'finance, gently',
          tagline: 'Anxious about money? Open your money calendar.',
          desc: 'Not sure when money comes in, when bills are due, or whether it will be enough? FloFi works like a calendar for your money: see where you will be in a week, a month, half a year or a year\u00a0— as deep as you want to go. It is easier than it sounds. Of everything we have made, it was the hardest to build and it is the most valuable to use. Just give it a chance.',
          platforms: ['iOS', 'macOS'],
          available: true,
        },
        {
          name: 'Switcher', sub: 'ru / en · keyboard',
          tagline: 'Typed a whole line and got "руддщ"? Switcher fixes it.',
          desc: 'You type, look up at the screen\u00a0— and it all came out in the wrong layout. Switcher notices, switches the layout and rewrites the words. Nothing to retype.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'Telesufler', sub: 'floating script · for your eyes only',
          tagline: 'Jumping from topic to topic? Keep your script in front of you.',
          desc: 'A Zoom call, a presentation, a screen recording. Add your text to Telesufler and it appears right by your camera. Look into the lens, say it out loud, and never lose the thread. Viewers never see it, even when you share your screen.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'Onit', sub: 'one task · always in sight',
          tagline: 'Opened Telegram and forgot what you were doing? Onit reminds you.',
          desc: 'You sit down to a task. Then a message in Telegram or WhatsApp, from there a link to YouTube, then a chat with ChatGPT about it… and the task is gone. Onit keeps a small plate on your screen showing what you are doing right now, and nudges you back when you wander off.',
          platforms: ['macOS'],
          available: true,
        },
      ],
      status: 'Available',
      cta: 'Open',
      download: 'Download',
    },
    cta: {
      eyebrow: 'Begin',
      h_pre: 'Try',
      h_hl: 'one app',
      h_post: ' today.',
      sub: 'You do not have to commit. Open it once. Use it for the one thing it does. See if it stays out of your way.',
      btn: 'See all apps',
    },
    footer: {
      tag: 'A small studio crafting calm apps for Apple platforms.',
      cols: [
        { h: 'Apps', l: ['CCV', 'VText', 'FloFi', 'Switcher', 'Telesufler', 'Onit'] },
      ],
      legal: '© 2026 Kelappa · Made slowly in Ubud · kelappa.studio',
    },
    mocks: {
      ccv: { file: 'villa_invoice.pdf', parked: 'parked · drag to take', eyebrow: 'The Portal', h: 'Drop anything. Take it anywhere.', count: '3 items parked' },
      vtext: {
        doc_title: 'Reply to Nyoman about the villa',
        doc_l1: 'Hi Nyoman, thanks for getting back. I wanted to follow up on the',
        doc_l2: 'invoice',
        listening: '⌘⇧ · listening · 0:08',
        said: '"could we move the payment to next monday since the bank holiday is on friday and i don\'t want this to get stuck in limbo"',
        actions: ['Insert', 'Shorter', 'Softer', 'Translate → EN'],
      },
      flofi: {
        eyebrow: 'This week · gentle view', left: '· left for the month', track: '↑ you are on track',
        days: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
        cats: ['Food & coffee', 'Rent & home', 'Fun & other'],
        today_pre: 'Today you have', today_post: 'for fun.',
      },
      switcher: {
        eyebrow: 'Compose · message', greeting: 'Hi Wira,',
        wrong: 'руддщ', right: 'hello', l1: '— could you take a look at the build?', l2: 'I think the api thing is broken again.',
        badge: 'RU→EN', toast: 'Switched to English', pair: '"руддщ" → "hello"',
      },
      telesufler: {
        eyebrow: 'screen sharing · slide 4 / 12', h: 'Q3 plan\u00a0— three bets',
        bullets: ['Launch the chat bot to 20 villas', 'Wire up the new pricing engine', 'Ship Telesufler 1.1'],
        you: 'You', on_top: 'always on top',
        prev: 'Hi everyone, thanks for jumping on.', line: 'Three updates\u00a0— shipping, hiring, Bali offsite.', next: 'First\u00a0— the bot is live in beta.',
        hidden: 'Hidden when you share screen',
      },
      onit: {
        doc_eyebrow: 'draft · q3 plan', doc_h: 'Three bets for Q3',
        task: 'Write the Q3 plan', running: '24:08 · running', still_on: 'still on: Write the Q3 plan',
        after: 'after 15 s in a messenger', diary: 'success diary · today', ask: '✎ what came out of it?',
        rows: [
          { name: 'Q3 plan\u00a0— three bets', time: '1h 20m', result: 'sent to the team, two bets cut' },
          { name: 'Reply to Nyoman',      time: '12m',    result: 'invoice moved to Monday' },
          { name: 'Fix the villa feed',   time: '2h 05m', result: null },
        ],
        total: '3h 37m',
      },
    },
  },

  ru: {
    meta: { title: 'Kelappa\u00a0— приложения для людей с\u00a0СДВГ' },
    nav: { apps: 'Приложения', principles: 'Принципы', contact: 'Контакты', lang: 'Язык' },
    hero: {
      eyebrow: 'Kelappa · Бали',
      h_pre: 'Приложения для людей с',
      h_hl: 'СДВГ',
      h_post: '.',
      sub_q: 'Всё забываете, отвлекаетесь и\u00a0опаздываете?',
      sub_a: 'Мы\u00a0делаем приложения, которые помнят за\u00a0вас.',
      cta_primary: 'Смотреть приложения',
      cta_secondary: 'Прочитать манифест',
    },
    manifesto: {
      eyebrow: 'Зачем мы\u00a0это делаем',
      h: 'Мы\u00a0сами живём с\u00a0СДВГ.',
      p1: 'Сейчас модно говорить, что СДВГ у\u00a0всех. Но\u00a0когда живёшь с\u00a0этим каждый день, это ни\u00a0с\u00a0чем не\u00a0спутаешь. Бесят глупые косяки. Бесит, что они бесят других. Бесит, что они мешают нормально жить.',
      p2: 'Поэтому мы\u00a0делаем приложения для себя\u00a0— чтобы жить и\u00a0работать наравне со\u00a0всеми. И\u00a0делимся ими с\u00a0вами: мы\u00a0были на\u00a0вашем месте и\u00a0понимаем, что вы\u00a0чувствуете. Большую часть этих косяков можно закрыть технологиями и\u00a0искусственным интеллектом.',
      p3: 'СДВГшник с\u00a0ИИ\u00a0и\u00a0правильными костылями\u00a0— возможно, суперчеловек. Но\u00a0это не\u00a0точно.',
    },
    principles: {
      eyebrow: 'Как мы\u00a0делаем',
      h: 'Шесть правил, которые мы\u00a0не\u00a0нарушаем.',
      items: [
        { n: '01', title: 'Один экран\u00a0— одно дело', body: 'Экран просит принять одно решение. Не\u00a0два и\u00a0не\u00a0боковую панель из\u00a0семнадцати пунктов.' },
        { n: '02', title: 'Без серий и\u00a0без стыда', body: 'Пропустили вторник? Приложение не\u00a0заметит. Привычки поддерживают, а\u00a0не\u00a0заставляют.' },
        { n: '03', title: 'Всё сохраняется', body: 'Пишите где угодно, закрывайте когда угодно. Вернётесь\u00a0— всё на\u00a0месте.' },
        { n: '04', title: 'Тихо по\u00a0умолчанию', body: 'Ноль уведомлений, пока вы\u00a0сами не\u00a0попросите. Ни\u00a0значков, ни\u00a0красных точек.' },
        { n: '05', title: 'Всё на\u00a0своих местах', body: 'Что было в\u00a0левом верхнем углу, там и\u00a0останется. Всегда.' },
        { n: '06', title: 'Для самого тяжёлого дня', body: 'Если работает в\u00a0туманный понедельник\u00a0— сработает в\u00a0любой день.' },
      ],
    },
    apps: {
      eyebrow: 'Наши приложения',
      h: 'Небольшие инструменты, которые не\u00a0мешают.',
      sub: 'Каждое убирает одну мелкую помеху, об\u00a0которую мозг с\u00a0СДВГ спотыкается по\u00a0десять раз на\u00a0дню. Большинством можно пользоваться уже сегодня.',
      items: [
        {
          name: 'CCV', sub: 'чёлка · портал для файлов',
          tagline: 'Бесит перетаскивать файлы между окнами? Просто закиньте их\u00a0в\u00a0чёлку.',
          desc: 'Простое приложение, которое превращает чёлку MacBook в\u00a0дополнительное место для файлов. Закинули файл, спокойно переключились на\u00a0нужное окно\u00a0— и\u00a0вытащили его туда. Файлы больше нигде не\u00a0теряются.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'VText', sub: 'голос → текст, где угодно',
          tagline: 'Бесит печатать, а\u00a0голосовые никто не\u00a0любит? Говорите\u00a0— VText напишет.',
          desc: 'Зажмите две клавиши и\u00a0говорите. Текст сам наберётся там, где стоит курсор, и\u00a0может сразу отправиться. Собеседник получит обычное сообщение, а\u00a0не\u00a0голосовое.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'FloFi', sub: 'финансы, бережно',
          tagline: 'Страшно, что будет с\u00a0деньгами? Откройте календарь своих денег.',
          desc: 'Непонятно, когда придут деньги, когда платить и\u00a0хватит ли\u00a0их? FloFi работает как календарь ваших денег: видно, что с\u00a0ними будет через неделю, месяц, полгода или год\u00a0— насколько захотите заморочиться. Это проще, чем кажется. Из\u00a0всего, что мы\u00a0сделали, это приложение было самым сложным в\u00a0разработке\u00a0— и\u00a0оно самое ценное в\u00a0жизни. Просто дайте ему шанс.',
          platforms: ['iOS', 'macOS'],
          available: true,
        },
        {
          name: 'Switcher', sub: 'ru / en · раскладка',
          tagline: 'Напечатали строку, а\u00a0там «ghbdtn»? Switcher исправит.',
          desc: 'Бесит, когда печатаете, смотрите на\u00a0экран\u00a0— а\u00a0всё набралось не\u00a0в\u00a0той раскладке. Switcher сам заметит, переключит раскладку и\u00a0перепишет слова. Перепечатывать ничего не\u00a0нужно.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'Telesufler', sub: 'плавающий текст · видно только вам',
          tagline: 'Скачете с\u00a0темы на\u00a0тему? Держите текст перед глазами.',
          desc: 'Звонок в\u00a0Zoom, презентация, запись видео с\u00a0экрана. Добавьте текст в\u00a0Telesufler\u00a0— он\u00a0появится прямо у\u00a0камеры. Вы\u00a0смотрите в\u00a0объектив, проговариваете текст и\u00a0ни\u00a0разу не\u00a0сбиваетесь с\u00a0темы. Зрители окно не\u00a0видят, даже при демонстрации экрана.',
          platforms: ['macOS'],
          available: true,
        },
        {
          name: 'Onit', sub: 'одна задача · всегда на\u00a0виду',
          tagline: 'Открыли Telegram и\u00a0забыли, что делали? Onit напомнит.',
          desc: 'Сели делать задачу. Зашли в\u00a0Telegram или WhatsApp, из\u00a0сообщения\u00a0— на\u00a0YouTube, оттуда\u00a0— в\u00a0ChatGPT обсуждать… и\u00a0уже не\u00a0помните, что хотели сделать. Onit держит на\u00a0экране плашку с\u00a0тем, чем вы\u00a0сейчас заняты, и\u00a0напоминает вернуться к\u00a0делу.',
          platforms: ['macOS'],
          available: true,
        },
      ],
      status: 'Доступно',
      cta: 'Открыть',
      download: 'Скачать',
    },
    cta: {
      eyebrow: 'Начать',
      h_pre: 'Попробуйте',
      h_hl: 'одно приложение',
      h_post: ' сегодня.',
      sub: 'Ничего не\u00a0нужно обещать. Откройте один раз. Используйте для того единственного дела, которое оно делает. Посмотрите, получится ли\u00a0оно незаметным.',
      btn: 'Все приложения',
    },
    footer: {
      tag: 'Небольшая студия, которая делает спокойные приложения для платформ Apple.',
      cols: [
        { h: 'Приложения', l: ['CCV', 'VText', 'FloFi', 'Switcher', 'Telesufler', 'Onit'] },
      ],
      legal: '© 2026 Kelappa · Сделано не\u00a0спеша в\u00a0Убуде · kelappa.studio',
    },
    mocks: {
      ccv: { file: 'villa_invoice.pdf', parked: 'на\u00a0парковке · тяните, чтобы взять', eyebrow: 'Портал', h: 'Положили\u00a0— забрали где угодно.', count: '3 файла ждут' },
      vtext: {
        doc_title: 'Ответ Ньоману по\u00a0вилле',
        doc_l1: 'Ньоман, привет, спасибо, что ответил. Хотел уточнить по\u00a0поводу',
        doc_l2: 'счёта',
        listening: '⌘⇧ · слушаю · 0:08',
        said: '«слушай а\u00a0можно перенести оплату на\u00a0следующий понедельник а\u00a0то\u00a0в\u00a0пятницу выходной и\u00a0не\u00a0хочу чтобы всё зависло»',
        actions: ['Вставить', 'Короче', 'Мягче', 'Перевести → EN'],
      },
      flofi: {
        eyebrow: 'Эта неделя', left: '· до\u00a0конца месяца', track: '↑ всё идёт по\u00a0плану',
        days: ['П', 'В', 'С', 'Ч', 'П', 'С', 'В'],
        cats: ['Еда и\u00a0кофе', 'Жильё', 'Развлечения'],
        today_pre: 'Сегодня можно', today_post: 'на\u00a0радости.',
      },
      switcher: {
        eyebrow: 'Новое · сообщение', greeting: 'Вира, привет!',
        wrong: 'ghbdtn', right: 'привет', l1: '— глянешь сборку?', l2: 'Кажется, api опять сломался.',
        badge: 'EN→RU', toast: 'Переключено на\u00a0русский', pair: '«ghbdtn» → «привет»',
      },
      telesufler: {
        eyebrow: 'демонстрация экрана · слайд 4 / 12', h: 'План на\u00a0Q3\u00a0— три ставки',
        bullets: ['Запустить чат-бота на\u00a020 виллах', 'Подключить новый расчёт цен', 'Выпустить Telesufler 1.1'],
        you: 'Вы', on_top: 'поверх окон',
        prev: 'Всем привет, спасибо, что подключились.', line: 'Три новости\u00a0— релиз, найм и\u00a0выезд на\u00a0Бали.', next: 'Первое\u00a0— бот уже в\u00a0бете.',
        hidden: 'Не\u00a0видно при демонстрации',
      },
      onit: {
        doc_eyebrow: 'черновик · план q3', doc_h: 'Три ставки на\u00a0Q3',
        task: 'План на\u00a0Q3', running: '24:08 · идёт', still_on: 'в\u00a0работе: План на\u00a0Q3',
        after: 'через 15 с\u00a0в\u00a0мессенджере', diary: 'дневник успеха · сегодня', ask: '✎ что получилось?',
        rows: [
          { name: 'План на\u00a0Q3\u00a0— три ставки', time: '1 ч\u00a020 м', result: 'отправил команде, две ставки убрали' },
          { name: 'Ответ Ньоману',           time: '12 м',     result: 'оплату перенесли на\u00a0понедельник' },
          { name: 'Починить фид вилл',        time: '2 ч\u00a005 м', result: null },
        ],
        total: '3 ч\u00a037 м',
      },
    },
  },
};

Object.assign(window, { COPY });
